galerija_images_homepage:
    pattern:  /
    defaults: { _controller: GalerijaImagesBundle:AlbumList:index }

galerija_images_upload:
    path:  /upload{albumId}
    defaults: { _controller: GalerijaImagesBundle:Image:upload, albumId: 0 }
    requirements:
        albumId: \d+

galerija_images_delete:
    path:  /delete
    defaults: { _controller: GalerijaImagesBundle:Image:delete }
    options:
        expose: true

galerija_album_delete:
    path:  /deletealbum
    defaults: { _controller: GalerijaImagesBundle:AlbumList:delete }
    options:
        expose: true

galerija_images_album:
    pattern:  /{albumId}
    defaults: { _controller: GalerijaImagesBundle:ImageList:albumById }
    requirements:
        albumId: \d+

galerija_images_user_album:
    pattern:  /photosby/{userId}
    defaults: { _controller: GalerijaImagesBundle:ImageList:albumByUser }
    requirements:
        userId: \d+

galerija_images_image_info:
    pattern:  /image/{imageId}
    defaults: { _controller: GalerijaImagesBundle:Image:showInfo }
    requirements:
        imageId: \d+

galerija_images_comment:
    pattern:  /postComment
    defaults: { _controller: GalerijaImagesBundle:Comment:submit }

galerija_images_like:
    pattern:  /commitLike{imageId}
    defaults: { _controller: GalerijaImagesBundle:Like:submit }
    requirements:
        imageId: \d+

galerija_tag_create:
    pattern:  /tagCreate
    defaults: { _controller: GalerijaImagesBundle:Tag:submit }
