galerija_images_homepage:
    pattern:  /
    defaults: { _controller: GalerijaImagesBundle:Default:index }

galerija_images_upload:
    path:  /upload{albumId}
    defaults: { _controller: GalerijaImagesBundle:Upload:index, albumId: 1 }
    requirements:
        albumId: \d+

galerija_images_delete:
    path:  /delete
    defaults: { _controller: GalerijaImagesBundle:Delete:index }
    options:
        expose: true

galerija_images_album:
    pattern:  /{albumId}
    defaults: { _controller: GalerijaImagesBundle:Default:albumById }
    requirements:
        albumId: \d+

galerija_images_user_album:
    pattern:  /photosby/{userId}
    defaults: { _controller: GalerijaImagesBundle:Default:albumByUser }
    requirements:
        userId: \d+

galerija_images_image_info:
    pattern:  /image/{imageId}
    defaults: { _controller: GalerijaImagesBundle:Image:showInfo }
    requirements:
        imageId: \d+

galerija_images_comment:
    pattern:  /postComment
    defaults: { _controller: GalerijaImagesBundle:Image:comment }

galerija_images_like:
    pattern:  /commitLike{imageId}
    defaults: { _controller: GalerijaImagesBundle:Image:like }
    requirements:
        imageId: \d+

galerija_tag_create:
    pattern:  /tagCreate
    defaults: { _controller: GalerijaImagesBundle:Default:tag }

galerija_tag_create:
    pattern:  /profileInfo
    defaults: { _controller: GalerijaImagesBundle:Profile:fullPanel }