galerija_images_homepage:
    pattern:  /
    defaults: { _controller: GalerijaImagesBundle:AlbumList:index }

galerija_images_upload:
    path:  /upload{albumId}
    defaults: { _controller: GalerijaImagesBundle:Image:upload, albumId: 0 }
    methods:  [POST]
    requirements:
        albumId: \d+

galerija_images_delete:
    path:  /delete
    defaults: { _controller: GalerijaImagesBundle:Image:delete }
    methods:  [POST]
    options:
        expose: true

galerija_image_edit:
    path:  /editImage{imageId}
    defaults: { _controller: GalerijaImagesBundle:Image:edit }

galerija_album_edit:
    path:  /editAlbum{albumId}
    defaults: { _controller: GalerijaImagesBundle:AlbumList:edit }

galerija_album_delete:
    path:  /deletealbum
    defaults: { _controller: GalerijaImagesBundle:AlbumList:delete }
    methods:  [POST]
    options:
        expose: true

galerija_album_default:
    path:  /defaultalbum
    defaults: { _controller: GalerijaImagesBundle:AlbumList:setDefault }
    methods:  [POST]
    options:
        expose: true

galerija_images_album:
    pattern:  /{albumId}/{page}
    defaults: { _controller: GalerijaImagesBundle:ImageList:albumById, page: 1 }
    requirements:
        albumId: \d+
        page: \d+

galerija_images_user_album:
    pattern:  /photosby/{userId}/{page}
    defaults: { _controller: GalerijaImagesBundle:ImageList:albumByUser, , page: 1  }
    requirements:
        userId: \d+
        page: \d+

galerija_images_image_info:
    pattern:  /image/{imageId}
    defaults: { _controller: GalerijaImagesBundle:Image:showInfo }
    requirements:
        imageId: \d+

galerija_images_comment:
    pattern:  /postComment
    methods:  [POST]
    defaults: { _controller: GalerijaImagesBundle:Comment:submit }

galerija_comment_delete:
    pattern:  /deleteComment
    defaults: { _controller: GalerijaImagesBundle:Comment:delete }
    methods:  [POST]
    options:
         expose: true

galerija_images_like:
    pattern:  /commitLike{imageId}
    methods:  [POST]
    defaults: { _controller: GalerijaImagesBundle:Like:submit }
    requirements:
        imageId: \d+

galerija_tag_create:
    pattern:  /tagCreate
    methods:  [POST]
    defaults: { _controller: GalerijaImagesBundle:Tag:submit }

