parameters:
    galerija_images.example.class: Galerija\ImagesBundle\Example

services:
    tag_manager:
        class:        Galerija\ImagesBundle\Services\TagManager
        arguments:
                  - "@doctrine.orm.entity_manager"
                  - "@form.factory"
                  - "@router"

    demo_user.registration_listener:
        class: Galerija\ImagesBundle\Handler\RegistrationHandler
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_subscriber }
            - { name: kernel.request }