parameters:
#    galerija_images.example.class: Galerija\ImagesBundle\Example

services:
#    galerija_images.example:
#        class: %galerija_images.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
