parameters:
    galerija_images.example.class: Galerija\ImagesBundle\Example

services:
    tag_manager:
        class:        Galerija\ImagesBundle\Services\TagManager
        arguments:
                  - "@doctrine.orm.entity_manager"
                  - "@form.factory"
                  - "@router"