<?php
namespace Galerija\ImagesBundle\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-05 at 22:24:28.
 */
class AlbumManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AlbumManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AlbumManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::getEditForm
     * @todo   Implement testGetEditForm().
     */
    public function testGetEditForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::findById
     * @todo   Implement testFindById().
     */
    public function testFindById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::findAutoSelect
     * @todo   Implement testFindAutoSelect().
     */
    public function testFindAutoSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::findAlbumInArray
     * @todo   Implement testFindAlbumInArray().
     */
    public function testFindAlbumInArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::recalculateCount
     * @todo   Implement testRecalculateCount().
     */
    public function testRecalculateCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Galerija\ImagesBundle\Services\AlbumManager::processDefaultImage
     * @todo   Implement testProcessDefaultImage().
     */
    public function testProcessDefaultImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
